### ISSUE TITLE
Missing Max Range Graph

### ISSUE THREAD

**Issue by fatherdoctor** [jprochazka/adsb-receiver#106]
Performed a 100% fresh install from the Git image at approx 1800 CST. Expanded file system and changed password only prior to running the install script.

/graphs/dump1090-localhost-range_imperial_nautical-24h.png?time=1456190097.919 is reporting 404 - Not Found

**Comment by jprochazka** [comment]
I take it from your report you ran install.sh after booting up the image and supplied the latitude and longitude of your receiver. This data is required by dump1090-mutability in order to calculate range. The range graph will not show data until an aircraft with positional data is seen by the receiver. If this is a new installation watch your dump1090 map once you see an aircraft icon on the map give the system 5 minutes in order to insure the cron job generating the hourly graphs has run. After 5 minutes has passed please check your hourly graphs to see if the range performance graph appears. Daily graphs are updated 2, 12, 22, 32, 42, and 52 minutes past the hour so you may not see these right away. If you still do not see range data let me know.

**Comment by fatherdoctor** [comment]
You got it on one. Since I was familiar with the process I just ran through and skipped lat long as all of the services I report on have a backup manual entry mode. Re-entering lat-long did the trick. Would it be possible to add an alt tag to the graph saying "Lat/Long required for this chart"?

**Comment by jprochazka** [comment]
Will do.

**Comment by jprochazka** [comment]
Added more pronounced warning to scripts.
