### ISSUE TITLE
Add update / install componants / uninstall componants UI

### ISSUE THREAD

**Issue by cy80rg101** [jprochazka/adsb-receiver#112]
Similar in function to fA's piAware web ui, this would allow user to 
- Update all to latest version
- Install additional componants
- Uninstall additional componants etc

Of course, this would just run the scripts etc we've been doing on the forums. 

Also good opportunity to push news about latest releases etc.

**Comment by jprochazka** [comment]
This is something I have thought about but being the development of the web portal is still in it's early stages of development, meaning it is going through major changes and additions, I do not feel comfortable giving the web server root access to a system. (God forbid an exploit is found...) I think a mechanism that detects when updates are available to each package is needed which can then inform said user an update is available. Updating and running the scripts via a shell would be the most secure way. News can be pushed without in the future without the need to allow the web server super user privileges.

I will leave this issue open until at least information regarding updates is automatically pushed to the administrator via the portal.

**Comment by dschaper** [comment]
Possible to create a new user, and give that user an entry in `/etc/sudoers.d/` and in that file allow the created user to execute a script that does the sudo actions. In the script you could limit the actions allowed, and in the sudoers.d file you could limit the extent of the users actions.

**Comment by Romeo-Golf** [comment]
I agree that having portal is able to trigger the updates would be ideal but in the mean time having it at least display the versions of the various additional components along side the portal version, plus an indication if any of these are not at the latest version, would help ensure that users get the most of all the hard work of the developers including jprochazka  :)

**Comment by jprochazka** [comment]
At this time this is too much of a security concern as far as I am concerned. Because of this I do not see a web based management system being created for this project any time soon. Too much access to the operating system has to be given for me to comfortablly allow such acts on a publically accessable inteface such as a web server.

Keep in mind building/installing/configuring this system many times requires root/sudo access. Even using /etc/sudoers.d/ would be an issue being the commands which would need to be allowed to maintain the system would be quite powerful in the hands of an attacker.

I feel it is best that updates be handled via the CLI as they always have been.
