### ISSUE TITLE
Links for "Aggregate Sites Statistics"

### ISSUE THREAD

**Issue by hbokh** [jprochazka/adsb-receiver#119]
- Planfinder Stats - missing an "e"
- Flightradar24 Stats - is not working because the ID is missing

The last one is because there is a mix up of both "flightRad**a**r24" and "flightRad**e**r24" in the code. When I fix ALL occurrences of "Rader" into "Radar", the last one is fixed. 

Running the March 7th release on an Rpi3.

**Comment by jprochazka** [comment]
Sometimes copy and paste can burn you...
This has been fixed in the following commits:

bd41a5875f6004a16fd40908e1db87ab00128bad
f71a3358ca29f3618161a4d88ab1cd1f1fc17de6

I am not sure if I updated the image however and will need to check that... But since you are already up and running back up the XML files found in /var/www/html/data use the upgrade instructions in the README.md file and choose to reinstall the portal.

Backup:

    sudo mkdir ~/backups
    sudo cp -R /var/www/html/data/* ~/backups/

Upgrade:

    cd ~/adsb-receiver
    git fetch --all
    git reset --hard origin/master
    ./install.sh

Restore:

    sudo cp -R /backups/* /var/www/html/data/

**Comment by ytwytw** [comment]
@jprochazka I just have the same issue

After a new fresh install, I cannot save Site ID for fr24 only

all other sites are fine
