### ISSUE TITLE
Add anything-sync-daemon option.

### ISSUE THREAD

**Issue by radiostationx** [jprochazka/adsb-receiver#153]
Hi Joe,
Is it possible to incorporate into scripts automated reduced i/o writes using anything-sync-daemon or similar.
Thanks.

**Comment by jprochazka** [comment]
I tried doing this a couple months ago and ended up destroying my RPi's file system. However I am willing to give it a go again if I can get information on the directories/configurations people are using which work.

_If added it will be marked as use at your own risk and only be made available on Raspberry Pi devices._

**Comment by mgunther68** [comment]
I'm using this config:
```
pi@raspberrypi:~ $ asd p
Anything-sync-daemon v5.76 on Raspbian GNU/Linux 8 (jessie)

 Systemd service is currently active.
 Systemd resync service is currently active.
 Overlayfs v23 is currently active.

Asd will manage the following per /run/asd.conf settings:

 owner/group id:     root/0
 target to manage:   /var/log
 sync target:        /var/.log-backup_asd
 tmpfs target:       /tmp/asd-root/var/log
 dir size:           8.6M
 overlayfs size:     4.3M
 recovery dirs:      none

 owner/group id:     root/0
 target to manage:   /var/lib/collectd
 sync target:        /var/lib/.collectd-backup_asd
 tmpfs target:       /tmp/asd-root/var/lib/collectd
 dir size:           118M
 overlayfs size:     7.9M
 recovery dirs:      none

 owner/group id:     root/0
 target to manage:   /var/www/html/graphs
 sync target:        /var/www/html/.graphs-backup_asd
 tmpfs target:       /tmp/asd-root/var/www/html/graphs
 dir size:           5.0M
 overlayfs size:     2.5M
 recovery dirs:      none
```

WARNING: The above works very well but if anything goes wrong (power cut or incorrect shutdown), it will require manual intervention. Especially when the /var/log dir is included: after a crash, the /var/log dir has NO sub-directories (in particular, NO lighttpd directory). This means lighttpd cannot start because it cannot find its log directory.
Crash recovery instructions here:
https://wiki.archlinux.org/index.php/Anything-sync-daemon#My_system_crashed_and_did_not_sync_back._What_do_I_do.3F

**Comment by radiostationx** [comment]
Tried asd yesterday on a test pi model b, ended up same way as Joe trashing system and having to format card, re-install adsb-receiver.

**Comment by Romeo-Golf** [comment]
looks like Jessie mounts the root file system with noatime already which should help ease the writes on flash media, hopefully modern SDHC/SDXC type cards have enough endurance for a reasonable lifetime... but cant hurt to be mindful of reducing IO where possible :)

**Comment by jprochazka** [comment]
At this time I do not plan on adding any such feature due to the fact doing so may open me up to a ton of "my receiver is screwed now" issues. For those interested in adding such a feature to their system I suggest doing a search of this issue tracker or better yet ask about it in the project forums. The answers are out there for those wishing to do this.
