### ISSUE TITLE
missing button

### ISSUE THREAD

**Issue by radiostationx** [jprochazka/adsb-receiver#174]
Hi joe,
Just tried latest release.
Carried out 

`cd ~/adsb-receiver
git fetch --all
git reset --hard origin/master 
./install.sh

` 

Next Button missing from foot of setup page, (lite options selected at ./install.sh)

On install of web portal
 
[IP_ADDRESS_OF_YOUR_DEVICE]/admin/install.php

unable to save admin name,email,password so really stuck on this one.

Also I noted that although I selected wlan0 for bandwidth monitoring, sys info guages did not function on this one.

**Comment by tbirdrv** [comment]
I just had the same problem.

I started with a fresh v2.0.0 image and got the /admin/install.php to work once, then I performed the update with

cd ~/adsb-receiver
git fetch --all
git reset --hard origin/master 
./install.sh

and now I can't complete the /admin/install.php setup because the Next Button missing from foot of setup page, (lite options selected at ./install.sh)

The data directory is writable.
The settings.class.php file is writable.

Rebooted the RPi and I don't get the portal page either. Dump1090 is feeding data to FlightAware.

**Comment by paranoidjack** [comment]
Seem to be having a similar problem: I keep getting redirected to /install/upgrade.php

The script says to delete: http://<IP_ADDRESS_OF_THIS_DEVICE>/admin/install.php - which doesn't exist  but I presume to be /install/upgrade.php

**Comment by jprochazka** [comment]
The Saturday morning I merged the 2.0.1 branch into master I meant to roll back the merge after having an issue with the image installation script while creating an image for the release and ended up forgetting to before falling asleep...

Anyways the PHP install script is now located at:
http://IP_ADDRESS_OF_YOUR_DEVICE/install/.

The merged changes work fine for upgrades and clean installs the only issue I have ran into was with the image setup script. I am working on the image setup script now so I will not be rolling back the merge now.

Please refer to the README.md file for updated instructions.
https://github.com/jprochazka/adsb-receiver/blob/master/README.md

I should have an image and official announcement posted within the next couple hours.
Sorry about any problems should have held off instead of staying awake trying to rush things...
