### ISSUE TITLE
Google Maps API Key for maps to display

### ISSUE THREAD

**Issue by jdwall** [jprochazka/adsb-receiver#207]
With the new changes to Googles' API we will need to utilize keys if accessing outside of `localhost`.  In `bash/portal/install.sh` there can be a new variable for there to be an API key designated. 

When trying to figure out where the API key would need to be set, it was more of a struggle than I thought. After reviewing `install.sh` I went to `/etc/lighttpd/conf-available/89-dump1090.conf` which led me to the final place where to set it!

To fix it one needs to go to line # 9 in `/usr/share/dump1090-mutability/html/gmap.html`

Before:
```
<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?libraries=geometry"></script>
```

After:
```
<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?key=$GMAPAPIKEYGOESHERE&libraries=geometry"></script>
```

**Comment by jprochazka** [comment]
Thanks for pointing this out. I am going to be overhauling the installation process very soon. When I do so I will modify things so that the Google Maps API key is asked for then stored within either the XML settings file or the database. I will also add the ability to change/specify the Google API key via the portal administration area.

**Comment by jprochazka** [comment]
Portal but not dump1090 maps now use the Google Maps API key which can be supplied by the user in the administration area. commit a8780e1e01c1a4f7414bfe90447d8b4c9213ed50.
