### ISSUE TITLE
Feature request: ability to view logs in the web portal

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#226]
In addition to the system syslog information it would be useful to view any log information created by the aggregation sites additional software, eg /var/log/piaware.log, in the web portal..

In addition to those of us who feel logs are worth reading every now and again, this could be useful to help with diagnosing and debugging issues with the aggregation site feeder software if their logs clearly indicate when connections to their servers are made/lost ;)

**Comment by jdwall** [comment]
I am pretty sure that this will be an easy implementation. I'll fork `2.2.1` and see what I can't knock out on my local system. Fair warning, it might not be as sexy as if @jprochazka did it, but, I'll look at the template documentation and see what I can do to blend it in the admin section.

**Comment by jdwall** [comment]
There are a few ways that I was thinking of approaching this:

- Simply symlink the log files and use the authentication layer that the `admin` section has to prevent unauthorized access.

- Integrate `rtail` which, while amazing, has the downside that you _must_ have an active SSH connection for it to tail log files. It's sleek, but has the downside of that. 

Since I don't expect it to be a feature used by the masses I am erring on the side of the latter. The former requires that the user actually download the whole file. Plus, with `rtail` one could `tail` the `dump1090` JSON output. 

Would definitely be open to hearing your feedback @Romeo-Golf. Let me know your thoughts!

**Comment by jdwall** [comment]
Let me know what you think of the first implementation of real-time log streaming into `adsb-receiver`. 

I added `ADS-B Logs` to the header, and can be enabled/disabled from `/admin` settings.

![New Header](http://i.imgur.com/8JxI5iX.jpg)

---

This option has no ability to search, but can do syntax highlighting (i.e. `err` is always red).

![No Search Option](http://i.imgur.com/rySpLSe.png)

---

This is with the search option

![Search Option](http://i.imgur.com/VJLQzg5.png)

Am I on the right track? I am finishing up the installation script right now and will open a PR under  `adsb-receiver/2.2.1` once done.

**Comment by Romeo-Golf** [comment]
Jacob,

It looks great thanks, would it be possible to have a sub-menu with toggle buttons for each log and perhaps even all/none?

Cheers,

RG

**Comment by jdwall** [comment]
I am using [frontail](https://github.com/mthenw/frontail), an open source project here on GitHub for the log streaming. I wonder, and this is going above my understanding, is whether @jprochazka might be able to help. If you can assist in pointing me to how I could make a shell command happen within the admin interface - which actually is more suitable for this feature anyways I think. In short, having a dropdown or checkbox option for log files to be tailed, within the admin interface rather than this all-or-nothing approach thus far.

The syntax on restarting the daemon is `frontail [options] [file ...]`. 

Great idea, @Romeo-Golf - It's been fun for me to be adding to this project.

**Comment by jdwall** [comment]
I have submitted the feature as #228. I have outlined what I have completed and where I still need to work on it, mostly in terms of post-install customizability.

**Comment by jprochazka** [comment]
The next gen portal is being developed to be independent of any receiver in order to allow a single portal installation to monitor multiple receivers. This would be a lot of data to store locally in someone's browser along with all the flight data from multiple receviers.
