### ISSUE TITLE
Field adsb_positions.aircraft always 0

### ISSUE THREAD

**Issue by webdoodle** [jprochazka/adsb-receiver#233]
Hello again,

So I've finally gotten around to digging through the MySQL data from your awesome project.  I noticed that the adsb_positions.aircraft field is always 0.  I'm assuming this should have the ID from adsb_aircraft.ID, so that you can join adsb_positions, adsb_flights and adsb_aircraft.  Is something broken?

Thanks for all you do!

**Comment by webdoodle** [comment]
I'm so sorry, I didn't see you closed this issue already.  I'll patiently wait for an update. :)

**Comment by webdoodle** [comment]
On a bright note, I did figure out how to update the flights.py and it is working!  Also, why did you remove the FAA tables?  Where can I get them?

**Comment by jdwall** [comment]
Were the FAA tables fully released? I don't recall them being. I do recall them being _in_ the code though. 

In the mean time, since I had previously downloaded the FAA database and made some `VIEWS` with the data, you can take these sql dumps and use this VIEW to get a "more complete" view on the aircraft. 

All SQL Databases: https://github.com/jdwall/dump1090-aircraft-information/tree/master/faa

MySQL VIEW to further enrichen the data shown: https://github.com/jdwall/dump1090-aircraft-information/blob/master/views/view_flights.sql

**Comment by webdoodle** [comment]
You rock!  It's folks like you that make open source work.  Thank you!

I'm sure I'll be busy analyzing this for a while...

**Comment by jdwall** [comment]
Happy to help and I appreciate the compliment. :)

**Comment by jdwall** [comment]
After looking more into the code, it does look like @jprochazka didn't remove the FAA piece. Were you not prompted for importing this data? https://github.com/jprochazka/adsb-receiver/blob/0486b39b0057970eecee7322a5b716c4e1d52b99/build/portal/html/admin/import.php

I haven't upgraded to `2.3.0` and am still running version 2.2.0. 

jdw
