### ISSUE TITLE
Performance Graphs - Move to SVG?

### ISSUE THREAD

**Issue by jdwall** [jprochazka/adsb-receiver#235]
Joe,

I have been looking at the performance graphs. Are you open to modifying some aspects of the code to output as SVG in lieu of PNG? That'd allow users to scale the images on-the-fly without quality loss. Or, adding in the ability to modify the default size of the charts. I'd personally be open to a less-structured performance graphs page _if_ that means that I'd be able to see more detail. Granted, I do feel it should be decided by the user and offer either option for users. 

I know there had also been a previous discussion about Highcharts. There were some licensing concerns with that from when I read #94. I have been mostly looking at projects with MIT licenses.  I've been looking at some `collectd` projects that output as SVG and `d3.js` based projects. D3 uses BSD-3-Clause, is that OK with you?

I'll still likely build it for myself, even if it never makes it into the master branch, but if there's an opportunity I can refine my approach and offer something back I would like to. Either way is fine with me!

**Comment by jprochazka** [comment]
Actually it is quite trivial to change to SVG using collectd. @Delekhan posted a merge request awhile back pertaining to a different issue but had some code to use SVG instead of PNG committed along side of the fix to the issue which were not merged at the time.

From reading what he wrote about the subject it seems quite trivial to switch over to SVG. Mainly telling collectd to generate SVG files instead and then finding a good way to compress the larger SVG files. He suggested possibly using Lighttpd to do the work.

https://github.com/jprochazka/adsb-receiver/pull/166
.
I guess offering the user an option to switch between these two formats easily would be where most of the work would come in. The easiest solution would be to give them the option during install/upgrade. Having the option available in the web portal administration area and getting the information to the collectd bash script securely would need some thought.

**Comment by jprochazka** [comment]
This suggestion has been added to my yet to be published TODO list for the new portal. I am going to close this issue due to the fact that In the near future the portal will reside in it's own repository. The new protal is a total rewrite and totally different creature making most all portal issues posted here invalid.
