### ISSUE TITLE
Add the ability to setup WiFi.

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-receiver#245]
Add a script which asks the user for information pertaining to their WiFi setup then install and configure wpa_supplicant so it is able to use this information to connect to their WiFi network.

The image can be setup to connect automatically as well by doing something similar to what the PiAware image does through a manual edit to a single file before booting up the image. THen configuring wpa_supplicant after the first boot.

**Comment by jprochazka** [comment]
**Headless wpa_supplicant setup**
_not tested..._

Add the following to /os/Raspbian/partition_setup.sh somewhere between the mount and umount lines

if [ -e /settings/wpa_supplicant.conf ] ; then cp /settings/wpa_supplicant.conf /tmp/2/etc/wpa_supplicant/wpa_supplicant.conf ; fi

**Comment by Romeo-Golf** [comment]
Given the increased prevelance of devices with wifi built in, such as the Raspberry Pi 3, this does seem like a useful feature...

As a precursor to any automated wifi setup functionality do you think its worth me knocking up some config to ask the user if they want to configure wifi during the installation?

If so it would be fairly easy to use a couple of whiptail dialogs to input the SSID/PSK etc, then use this to generate the /etc/wpa_supplicant/wpa_supplicant.conf plus confirm wlan0 is configured in /etc/network/interfaces ...

Rather than restarting networking it may be more useful to simply leave this to take effect on next restart.

Finally would it be worth saving the inputted values to the central config file such that with some further work it could be used to allow unattended installation with wifi support?

ie user downloads latest image, flashes to SD card, mounts the SD, copies over their config, unmounts the SD, moves it to the Pi ready for direct deployment to somewhere out of reach of wired Ethernet and/or a screen plus keyboard :)

Obviously this would require the image to run something on startup to check if a config has been provided with automated install enabled, and thus configure then enable wifi prior to attempting to run the first part of the install which expects network connectivity... but shouldnt be much more complex than that..

Anything automated is perhaps something to target for a release after 2.7.0, but are you happy for me to add the dialogs to allow the user to configure and enable wifi as part of the interactive install ?

**Comment by jprochazka** [comment]
> Obviously this would require the image to run something on startup to check if a config has been provided with automated install enabled, and thus configure then enable wifi prior to attempting to run the first part of the install which expects network connectivity... but shouldnt be much more complex than that..

Raspbian has been able to do this out of the box since about mid 2016. Simply place your settings in /boot/wpa_supplicant.conf on your image and your done. On boot it will move this file to /etc/wpa_supplicant/wpa_supplicant.conf.
