### ISSUE TITLE
Weather information via json ?

### ISSUE THREAD

**Issue by kalustian** [jprochazka/adsb-receiver#247]
Hello,

I am curious if weather information like METAR, TAF, etc can be shown as part of the information presented for traffic at http://192.168.1.143/dump1090/data/aircraft.json or dump978 ?

is it possible to add the uat2text in the below bash line and get the weather out of it ?

rtl_sdr -d stratux:978 -f 978000000 -s 2083334 -g 48 - | /home/pi/adsb
-receiver/build/dump978/dump978 | **/home/pi/adsb-receiver/build/dump978/uat2text |** /home/pi/adsb-receiver/build/dump978/uat2json /var/www/html/dump978/data | /home/pi/adsb-receiver/build/dump978/uat2esnt | /bin/nc -q1 127.0.0.1 30001 &

Thanks-

**Comment by jdwall** [comment]
Can you share the exact part of stratux code, since it does pass along METAR/TAF/etc information that you took the `rtl_sdr` piece from? That might give some ideas on how to formally incorporate it. 

For what it is worth, I'd like to see the option for displaying the information too, a lot like how Skyvector does it. That'll be above my understanding on how to do it, so, I am not the person to do it.

**Comment by kalustian** [comment]
I dont have the startux code...I was just wondering if we can get the weather information via json similar as the aircraft information.
