### ISSUE TITLE
Feature request: Ability to set location and thus local timezone and keymap during install

### ISSUE THREAD

**Issue by Romeo-Golf** [jprochazka/adsb-receiver#250]
There are a number of localisation considerations which it may be possible to simplify by asking the user to confirm their location during install, either by selecting a country or entering LAT/LON coordinates if known, these include:

Timezone
Keyboard map
System locale
NTP server pool (relates to another feature request)

I seem to recall most distributions as for this information during the installation so if not set as part of the Rasperbian image then perhaps worth asking the users to enter this as part of the adsb-receiver script, ideally with the option to confirm existing settings and skip further questions when the script is being used to reinstall or update the component software.

**Comment by Romeo-Golf** [comment]
Would I be correct to assume that the Time Zone setting in the admin portal is only used for portal related functions such as the graphs, and does not set the system timezone in `/etc/localtime` ?

**Comment by Romeo-Golf** [comment]
related to https://github.com/jprochazka/adsb-receiver/issues/160 ? :)

**Comment by Romeo-Golf** [comment]
I'm not sure if the same data can be obtained via Google API's but the following appears to allow country code, timezone and language to be derived from LAT/LON:

http://www.geonames.org/export/web-services.html

http://api.geonames.org/timezoneJSON?lat=47.01&lng=10.2&username=demo

http://ws.geonames.org/countryCodeJSON?lat=49.03&lng=10.2&username=demo

Would it be preferable allow the user to override the derived values?

**Comment by jprochazka** [comment]
Times saved to the database are converted to UTC before writing the data. As far as timestamps which are related to MLAT I am pretty positive they are converted to UTC as well before being sent to the MLAT server.  This being said local time does not matter as far as any of the software or the portal is concerned which is why I never bothered to add this option in the past.

There is another open issue, issue #160 , which you pointed out which once addressed should handle this. As far as automating things this might go beyond the scope of the project in that some sort of database with not only a locations time zone but also the locale and keyboard layout for every possible location would be needed. I think it would be best to use dpkg reconfigure to set such items so time can be spent focusing on the receiver side of things instead of system configuration.

sudo dpkg reconfigure tzdata
sudo dpkg-reconfigure locales
sudo dpkg-reconfigure keyboard-configuration

It defiantly is an interesting idea. Maybe down the road when feature requests pertaining to the receiver side of things are caught up and time allows it...
