### ISSUE TITLE
Update after v2.5 installed

### ISSUE THREAD

**Issue by radiostationx** [jprochazka/adsb-receiver#337]
Can somebody please tell us how to update to romeo golf v2.6 or v2.7 and put the instructions in the wiki please.
If I follow wiki instructions to update my system  it remains at v2.5 .
Is v2.7 the latest stable maintained version of this project ?

**Comment by radiostationx** [comment]
Installed romeo golf v2.6 which cured my planefinder client issue which halted whole install of  v2.5 . When installing 2.6 installer window text is v2.5, system info in portal is v2.5.

**Comment by Romeo-Golf** [comment]
Hi,

The current RG branches are as follows:

- [2.5.1](https://github.com/Romeo-Golf/adsb-receiver/tree/2.5.1)   Release Candidate          Bugfix only release to bring componennt packages up to latest versions
- [2.6.0](https://github.com/Romeo-Golf/adsb-receiver/tree/2.6.0)   Beta release                    New feature release, currently being tested and considered stable
- [2.7.0](https://github.com/Romeo-Golf/adsb-receiver/tree/2.7.0)   Alpha release                  Longer term development work, not currently being tested and should be considered unstable.. aka broken

The portal upgrade script, and associated version number, have yet to be updated on any of these branches so will continue to say 2.5.0 once installed but this is on the list of things to be fixed before any of these branches can be considered release worthy.

Just to be clear that all of these branches have been updated to use the latest stable versions of the contributing components, including MLAT Client, Plane Finder and FlightAware's PiAware so it is *not* required to upgrade to 2.6.0 to obtain these..

Unfortuantely there are a few more steps required to revert to a previous version than there are to upgrade so I would recommend that anyone who wishes to assist with the testing, but who is not overly familiar with git, at least starts off with the 'stable' 2.5.1 release.

The following instructions should switch a fresh or existing install of any version of the adsb-exchange script to the relevant RG branch, and for Raspberry Pi I would recommend starting with @jprochazka's pre-built 2.5.0 image:

https://github.com/jprochazka/adsb-receiver/releases

Then run the commands below, as the default 'pi' user, to update to either the 2.5.1 or 2.6.0 branches:

**Romeo-Golf [2.5.1](https://github.com/Romeo-Golf/adsb-receiver/tree/2.5.1)** 
```
export PROJECTBRANCH=2.5.1
cd ~/adsb-receiver
git remote rm origin
git remote add origin https://github.com/romeo-golf/adsb-receiver.git
git fetch
git checkout -b ${PROJECTBRANCH} origin/${PROJECTBRANCH}
./install.sh
```

**Romeo-Golf [2.6.0](https://github.com/Romeo-Golf/adsb-receiver/tree/2.6.0)**
```
export PROJECTBRANCH=2.6.0
cd ~/adsb-receiver
git remote rm origin
git remote add origin https://github.com/romeo-golf/adsb-receiver.git
git fetch
git checkout -b ${PROJECTBRANCH} origin/${PROJECTBRANCH}
./install.sh -b ${PROJECTBRANCH}
```

Regards.

**Comment by cy80rg101** [comment]
Hi all - just to check, do I have to actually install and configure 2.5 before I can then switch to 2.6?

I followed the original 2.5 install routine up to the point of installing - *didnt install at this point*

Then ran the 2.6 update instructions as above... installed, all installs failed due to "unable to install a required package". 

Was assuming the update to 2.6 would "just" update the packages, and could then be installed from there? 
(hence why I waited till 2.6 was cloned in before trying to install).

**Comment by radiostationx** [comment]
cy80rg101, yes I would install jpro v2.5 and configure this fully before upgrading to v2.5.1 or V2.6.

**Comment by cy80rg101** [comment]
Thanks, Radiostationx, I'll do that...

I have 2.5 installed (well, just the web ui and Flightaware - everything else (planefinder, adsbexchange etc) failed due to the issue above. 

Couple of related questions if I may:

1. What "benefits" does 2.6 give over 2.5?
2. My Orange Pi is set up to use the SD for boot only, the root FS is running from a usb HDD. 
I believe this gives me the ability to use the "experimental" functions, logging etc?

How "experimental" is that feature - afair it's been in for a while?

**Comment by radiostationx** [comment]
v2.5.1 onwards, include latest feeder package versions for all feeder software.

v2.6 small additions listed at top of this page
[https://github.com/Romeo-Golf/adsb-receiver/blob/2.6.0/CHANGELOG.md](url)

**Comment by cy80rg101** [comment]
Hi RadioStationX, 

Installed and set up JP's original 2.5 branch - installed and running. 

Ran the update instructions exactly as above - for 2.6.0, and I get the following after running ./install... 

Press enter to continue...

  The ADS-B Receiver Project Preliminary Setup Process

  Pulling the latest version of the ADS-B Receiver Project repository...
  ------------------------------------------------------------------------------

  Switching to branch {PROJECTBRANCH}...

error: pathspec '{PROJECTBRANCH}' did not match any file(s) known to git.

  Fetching branch {PROJECTBRANCH} from origin...


  Performing hard reset of branch {PROJECTBRANCH} so it matches origin/{PROJECTBRANCH}...

fatal: ambiguous argument 'origin/{PROJECTBRANCH}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

  ------------------------------------------------------------------------------
  Finished pulling the latest version of the ADS-B Receiver Project repository....

Press enter to continue...

Am I supposed to put the version number in the {}, i.e 
{2.6.0} rather than 
{PROJECTBRANCH}?

**Comment by cy80rg101** [comment]
Hmm, I dont think the branch update worked properly, although the installation script continued, it failed at PFCLient - which leads me to believe it's not actually using the new installers, hence it's not the updated branch?

**Comment by cy80rg101** [comment]
This is the error I get trying to install PFCLient through the installer... 

The package "pfclient" could not be installed.
>
>   ------------------------------------------------------------------------------
>   PlaneFinder ADS-B Client setup halted.
>
> dpkg-deb: error: `/home/pi/adsb-receiver/build/planefinder/pfclient_3.7.1_armhf.deb' is not a debian format archive
dpkg: error processing archive /home/pi/adsb-receiver/build/planefinder/pfclient_3.7.1_armhf.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 /home/pi/adsb-receiver/build/planefinder/pfclient_3.7.1_armhf.deb

  Checking that the PlaneFinder ADS-B Client package was installed properly...


  INSTALLATION HALTED!
  UNABLE TO INSTALL A REQUIRED PACKAGE.
  SETUP HAS BEEN TERMINATED!

The package "pfclient" could not be installed.

  ------------------------------------------------------------------------------
  PlaneFinder ADS-B Client setup halted.

**Comment by radiostationx** [comment]
https://github.com/jprochazka/adsb-receiver/issues/328

**Comment by cy80rg101** [comment]
Thanks RadioStationx, 

To upgrade from the original 2.5 branch, I ran the new install line:

export PROJECTBRANCH=2.5.1 && ./install.sh

Unfortunately, prior to that I followed the upgrade instructions for the new 2.6.0 - running the command above references the 2.5.1 version... seemed to run, still wouldnt install any of the 3rd party feeds. 

Then, spotting the issue, I followed the instructions for 2.5.1 install, which certainly switched the branch back to 2.5.1, downloaded etc. 

Running the new install line 

export PROJECTBRANCH=2.5.1 && ./install.sh

- placing this at the end of the instructions for 2.5.1, the script installed FA as expected, but then fell over again, trying to install PF, with the same issues as above?

**Comment by radiostationx** [comment]
CY80,
I would try rolling back

`cd ~/adsb-receiver
git fetch --all
git reset --hard origin/master
./install.sh

Following the complete install back at the origin master including web portal.

Try the method
export PROJECTBRANCH=2.5.1 && ./install.sh 
again
`

**Comment by cy80rg101** [comment]
Bah - still no joy :( 

Silly question - in the above instructions, are the 

{PROJECTBRANCH}

manual place holders, for the user to enter the desired branch / version number?

I've been simply copy n pasting from the instructions for 2.6.0 above - but including your 

./install.sh -b 2.6.0

which I note you've replaced 

{PROJECTBRANCH}

with 

2.6.0 

i.e manualy declared the version number... 

Should all {PROJECTBRANCH} be treated like this?

(I'm kinda assuming the first line... 

export PROJECTBRANCH=2.6.0

declares the var PROJECTBRANCH as 2.6.0?)

**Comment by Romeo-Golf** [comment]
For 2.5.1 you must set the $PROJECTBRANCH variable to prevent the install script from reverting to the 'latest' version from @jprochazka's branch...

But for 2.6.0 this is only used for convenience so you could use the following:


```

cd ~/adsb-receiver
git remote rm origin
git remote add origin https://github.com/romeo-golf/adsb-receiver.git
git fetch
git checkout -b 2.6.0 origin/2.6.0
./install.sh -b 2.6.0

```


Regards.

**Comment by jprochazka** [comment]
This is more instructional so I am marking this as a question and closing it so I can more easily navigate the issues as I begin to once again address them.
