### ISSUE TITLE
Remove unnecessary variables.

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-receiver#348]
There are way too many unnecessary variables present in the bash scripts brought over to the master branch which only complicate development such as redundant paths and names of items being installed. In order to simplify things these unneeded variables should be remove and hard coded text be put back in their place.

A script named dump1090-mutability.sh will always install dump1090-mutability so there is no need to added a "COMPONENT_NAME" variable nor do any of the "COMPONENT_*" variables need to exist. Using these variables only make the script overcomplicated and confusing to making troubleshooting problems such as the path issue present when moving the compiled binary more troublesome than such a simple issue should have been.

TODO: Remove all unnecessary variables.

- [x] decoders/dump1090-fa.sh
- [X] decoders/dump1090-mutability.sh 
- [X] decoders/dump978.sh 
- [x] feeders/adsbexchange.sh 
- [x] feeders/flightradar24.sh 
- [X] feeders/piaware.sh 
- [x] feeders/planefinder.sh 
- [x] extras/abovetustin.sh 
- [x] extras/beastsplitter.sh 
- [x] extras/duckdns.sh

**Comment by Romeo-Golf** [comment]
The idea was that instead of writing a new script for each new "component", which contains many lines of code that is duplicated in other scripts but not (yet) moved to functions in the main scripts..

Thus by parameterizing the variable names it allows for far easier comparison of the scripts for similar components, such as the multiple dump1090 forks, or to take the common code from the existing feeder scripts to make a generic feeder.

IMHO the key to scalability is flexibility, and being able to reduce the work required to add new features or feeders seem like something that would be both useful and well received... do you not agree?
