### ISSUE TITLE
Issue with dump978-maint.sh

### ISSUE THREAD

**Issue by BillDunn** [jprochazka/adsb-receiver#351]
When setting up dump978 yesterday (10/3/17) it didn't work with v 2.6.0. Looked at logs and saw issues with dump978-maint.sh. As it turns out a /dump978 was left off of 3 entries. Here is a copy with the original build # commented out.
#!/bin/bash
#rtl_sdr -d FA0002 -f 978000000 -s 2083334 -g 48 - | /home/pi/adsb-receiver/build/dump978 | tee >(/home/pi/adsb-receiver/build/uat2json /var/www/html/dump978/data) | /home/pi/adsb-receiver/build/uat2esnt | /bin/nc -q1 127.0.0.1 30001
#Start dump978 without logging.
while true; do
    rtl_sdr -d FA0002 -f 978000000 -s 2083334 -g 48 - | /home/pi/adsb-receiver/build/dump978/dump978 | tee >(/home/pi/adsb-receiver/build/dump978/uat2json /var/www/html/dump978/data) | /home/pi/adsb-receiver/build/dump978/uat2esnt | /bin/nc -q1 127.0.0.1 30001 | /home/pi/adsb-receiver/build/dump978/uat2text
    sleep 15

Works great now, Thanks,
Bill Dunn

**Comment by jprochazka** [comment]
If this was taken from the master branch of this project it was likely due to an error on my part during the variable clean up work I have been doing recently as stated in Issue #348. Anyways the issue has been addressed and a commit made to the master branch.

Fix in commit 4407249b294969d1c3f6aa46623e612fcfddb124.

For the record as an example the path to the repository and binaries is now:
`/home/pi/adsb-receiver/build/dump978/dump978` 
And the path to the maintainance script is now:
`/home/pi/adsb-receiver/build/dump978`

No change is needed being the dump978 build directory is recreated whenever a dump978 reinstall is executed.

Thanks for reporting the issue. Also please keep in mind at this time the master branch is being brought up to date with all the third party changes made in my recent absence. Until v2.6.0 is released please treat the master branch as a work in progress. However, this being said I am open to and thankful for
 reports such as this pertaining any issues encountered by those wishing to test things out.
