### ISSUE TITLE
Added mapzen and google maps API key, map still default

### ISSUE THREAD

**Issue by radumalica** [jprochazka/adsb-receiver#369]
I added the API key from mapzen during installation, and also provided google maps API key in the web interface but when going to portal and showing the live map, it still uses openlayers map. No option to change that.

**Comment by jprochazka** [comment]
First off keep in mind dump1090-mutability only supports Bing Maps and Mapzen. These keys must be entered at install/reinstall time or manually added to the file /usr/share/dump1090-mutability/html/config.js. The Google Maps API key you are able to enter into the administration area of the portal only works with the portal itself. The maps which use this key are also only available after installing the portal with the advanced features enabled.

The Bing Maps API key appears to be inserted properly in the dump1090-mutability's config.js file and the Bing Maps option does appear on my dump1090-mutability map when clicking the icon shaped like stacked squares in the upper right hand side of the map. However, I cannot test Mapzen at this time due to the fact I am unable to access their sign in or sign up pages at this time for some reason.

Feel free to reopen this issue if in fact you are still having this issue after reading over this post.
