### ISSUE TITLE
Error 500 on web portal

### ISSUE THREAD

**Issue by flightcode** [jprochazka/adsb-receiver#370]
When installing adsb-receiver with the web portal, and using a remote sql database, the web portal doesn't work.

When I initially installed, the web portal install page worked, but once I completed the form, it won't load, and provides an HTTP Error 500. The sql table wasn't created on the database either.

**Comment by jprochazka** [comment]
When the user is created by the script the host is set to local host allowing access to the server from that login to only be allowed from the local database server. This has been fixed in commit e63e32773b6a3e685409a4d8b42df400b0d7fce8. You can fix existing installations by running the following commands on the remote MySQL/MairiaDB server or changing the host value for the user from localhost to % in phpMyAdmin, etc..

```
mysql -uroot -p -h <DATABASE_SERVER_HOSTNAME>
UPDATE user SET host='%' WHERE user='<DATABASE_USER_NAME>';
FLUSH PRIVILEGES;
```
