### ISSUE TITLE
No information of Flights in MySQL db

### ISSUE THREAD

**Issue by miloit** [jprochazka/adsb-receiver#374]
Hello, 
I have nothing written into my db.
Also Flights Seen is empty and performance graphics tells me error 404

What's wrong?

**Comment by jprochazka** [comment]
When the user is created by the script the host is set to local host allowing access to the server from that login to only be allowed from the local database server. This has been fixed in commit e63e32773b6a3e685409a4d8b42df400b0d7fce8. You can fix existing installations by running the following commands on the remote MySQL/MairiaDB server or changing the host value for the user from localhost to % in phpMyAdmin, etc..

```
mysql -uroot -p -h <DATABASE_SERVER_HOSTNAME>
UPDATE user SET host='%' WHERE user='<DATABASE_USER_NAME>';
FLUSH PRIVILEGES;
```
