### ISSUE TITLE
Amy development ongoing?

### ISSUE THREAD

**Issue by miloit** [jprochazka/adsb-receiver#379]
Hello IS there any development ongoing or is it dead again?

**Comment by bctrainers** [comment]
Might be worthwhile checking https://github.com/jprochazka/adsb-receiver/network for any forked projects based from this one.

**Comment by jprochazka** [comment]
Yes it is. I am in the midst of a total rewrite which will become version 3. I apologize for neglecting the current code. I have been spending my free time on v3.x. Honestly I should have stopped in more often to address these issues sooner... I will be taking a break from work on v3 in order to address the newer issues here this weekend.

More details on what I have been working on can be found here:
https://www.adsbreceiver.net/2018/02/24/what-i-have-been-doing-over-the-past-couple-months/
