### ISSUE TITLE
installation failed v2.6.1 mutability version

### ISSUE THREAD

**Issue by radiostationx** [jprochazka/adsb-receiver#389]
failed on pi3 when installing postfix as mirror not contactable.

 so tried apt-get

`pi@raspberrypi:~ $ sudo apt-get update
Err:1 http://mirrordirector.raspbian.org/raspbian stretch InRelease            
  Temporary failure resolving 'mirrordirector.raspbian.org'
Err:2 http://archive.raspberrypi.org/debian stretch InRelease                  
  Temporary failure resolving 'archive.raspberrypi.org'
Reading package lists... Done             
W: Failed to fetch http://mirrordirector.raspbian.org/raspbian/dists/stretch/InRelease  Temporary failure resolving 'mirrordirector.raspbian.org'`

**Comment by jprochazka** [comment]
Looks like a DNS issue more than likely pertaining to either your Internet connection or an issue on the raspbian.org side. Make sure your RPi is in fact connected to the Internet and able to resolve other domains such as GitHub.com, etc.. If you are able to resolve other domains on your RPi allow a little time to pass to make sure things are in order on the raspbian.org side of things and give it another shot.

**Comment by orionjb2001** [comment]
Same problem.  Also cannot reset my password via wordpress. Have sent an email but no response.

**Comment by orionjb2001** [comment]
Hi Joe,

Hope this finds you.  I am trying to login into your project page adsbreceiver.net via the  wordpress   system (Ithink) with my user id.  It is not working, so I have used the lost password feature but the following wordpress error message:

“The email could not be sent.
Possible reason: your host may have disabled the mail() function.”

??

**Comment by jprochazka** [comment]
It is on pretty much it's own server on AWS so it was a mess up on my end when entering settings. Looks like I used a bad API key from the old site for the service I use to send mail from the web server. Anyways I reset the API key and tested things out and things appear to be working.

As for this topic I will more look more thoroughly into it this issue when I get home and have access to one of my Raspberry Pi's. In the mean time you can give this a try.

Open /etc/resolv.conf...

`sudo nano /etc/resolv.conf`

Add the following lines to this file to use Google's public DNS servers:

```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

**Comment by orionjb2001** [comment]
Hi Joe, 

 

Thanks.  Password reset now all good.  Install upgrade has now also worked, although, when I went into the post portal install, which has changed by the look of it, I was sent to a login page (new for me at this step) /admin/login.php.  It wanted a user ID and password.  Now I tried the user id and password just reset, no good, so went to password reset, both my user id and email address were not recognisesd.  I even tried the pi / putty id and password, not good.  So I have not completed the usual set up for the portal, everything seems to work though, but not sure if set up correct without that portal set up.

 

Jeff

**Comment by orionjb2001** [comment]
Hi Joe, password reset ok.  Tried install upgrade again and it worked this time, however, although, when I went into the post portal install, which has changed by the look of it, I was sent to a login page (new for me at this step) /admin/login.php.  It wanted a user ID and password.  Now I tried the user id and password just reset, no good, so went to password reset, both my user id and email address were not recognised.  I even tried the pi / putty id and password, no good.  So I have not completed the usual set up for the portal, everything seems to work though map wise, but not sure if set up correct without that portal set up. Now I still one unit working on the old version, 2.5.0 and the new unit in the system info is showing 2.6.1 but I don't have performance graphs (??due to not finishing portal install??))

Jeff

**Comment by jprochazka** [comment]
The login and password for your receiver will be totally separate from what you set on adsbreceiver.net. Everything receiver related on your device is it's own thing and none of the data your receiver has collected is shared with adsbreceiver.net. It should be the same as what you set when you first installed the portal. Try resetting the password for your portal on your device using the forgot password link on your portal. If that does not resolve the issue for some reason I will whip up a solution which does the same without the email aspect.

**Comment by orionjb2001** [comment]
Hi Joe,

 

That makes  sense re link between adsb net and the units.  The portal login for the 2.5.0 unit still works, it should be the same for the second unit.  Leave it with me for a tic, working on a fix, 😉

 

Jeff

**Comment by jprochazka** [comment]
BTW testing things out now.
Was this issue experienced using the image or after upgrading an existing installation?
If so from what version of the project and what version OS Raspbian Jessie or Scratch?

**Comment by jprochazka** [comment]
Installation on a virgin installation of Raspbian Lite November 2017 using the cloned version of the repository shows no such issues when installing Postfix. Moving on to the dump1090-mutability image although which image used does not matter in this case.

Wondering if WiFi was set up? Using one of the images this will be one of the first things installed from the Internet due to the fact I did not take into account preinstalling Postfix when initially setting up the images this time around...

**Comment by jprochazka** [comment]
Spent the last two+ hours doing a virgin Raspbian Lite November 2017 installation, Raspbian Lite November 2017 2.6.1 dump1090-mutability image installation, and upgraded an instance of the Raspbian Lite September 2017 Stretch v2.6.0 2017 with dump1090-fa preinstalled image. I cannot recreate this issue.

Again I recommend making sure your device is in fact connected to the Internet and able to properly resolve addresses such as archive.raspbian.org.

If in fact your device is connected and the issue does in fact still persist even without changes effecting this issue being made to the scripts let me know. In order to troubleshoot things further I will need more information on your setup being I was unable to recreate the issue in the previously mentioned environment.

**Comment by radiostationx** [comment]
Hi Joe,
My issue was indeed a DNS ,now fixed.
I had originally set fixed IP using the name sever address as my routers ip address,
in the file  /etc/dhcpcd.conf
This did not work when I tested the connection to the wan as you reccommended. 
I edited the file and replaced the name sever address with 8.8.8.8 (google) and all was well & postfix installed along with the portal.

I opted out of postfix email alerts but the whole portal install was stopped by postfix install which I did not want anyway. I could not get the station/decoder going in basic fashion with the image on the card, I think I would have been able to if I had used  v2.5.
Something to think about perhaps.

Running now so all okay.
Thanks Joe.

**Comment by jprochazka** [comment]
Postfix... Exim... Honestly the same thing when it comes to this kind of setup. Both are great MTA's and honestly no one not running an actual Internet mail server sending AND receiving emails should mind either way. However, Postfix works with PHP out of the box so IMO Postfix > Exim. Earlier issue pertaining to FUD about Postfix blew my mind and would have honestly not contributed to your issues.

Either way whatever works for you. Personally spent the evening trying to recreate Postfix issues and was unable to so since you are up and running now however you set up your setup I will mark this as invalid being I could not recreate it nor got information on how to. :)

**Comment by orionjb2001** [comment]
Hey Joe.  
It appeared for my second unit, I am not sure what id and password I used when first set up, so I just cloned the first unit, re imaged the second unit, ran it through an upgrade, just to be sure the set up was good and as mentioned before, I was able to log in to the portal setup, using the same id and password.  I found though, when upgrading the first unit, I did not have to change anything in the portal set up, it was all as previously selected. 

The only thing I needed to change for the second unit, was where the Flightaware link pointed to, changing it to my second unit Flightaware details.  Now I chose not to use Postfix, these units are purely used as ADSB trackers, nothing else.  Otherwise, all is working well still.   

Oh, just one little observation, during the initial set up for the second unit, I chose to upgrade the OS.  When it got to starting the mutability upgrade, it froze again.  Thinking about what happened with the first unit upgrade, it too froze on the first attempt to upgrade, after the OS upgraded but installed fine on the second attempt.  So I simply ran the 2nd unit to upgrade again, declined the OS upgrade (already done) and it worked perfectly.

Jeff
