### ISSUE TITLE
Server issues?????

### ISSUE THREAD

**Issue by orionjb2001** [jprochazka/adsb-receiver#400]
I am not sure how github works, but I have noticed your work, to download or upgrade, has been very slow lately. Like right now, I am downloading the latest muta version and it is going to take 5 hours, normal takes about 2 minutes. :(

**Comment by jprochazka** [comment]
I have not had any issues pushing or pulling to the repository. Out of curiosity I have noticed on my home network since switching providers that my router assigns an IPv6 address to my machines. When this would happen running something as simple as `sudo apt update` I would see in the output an IPv6 address as if it was trying to use IPv6 to download the update. After awhile it would, I am guessing, time out and switch to IPv4 which would download said update with no problem at least until the next request is made then it would stall on the IPv6 address again.

To resolve the problem I disable IPv6 DHCP in my router and had no issues since.

Example output of which I am talking about.
![ipv6-issue](https://user-images.githubusercontent.com/2583357/37859865-32a6c46c-2ef1-11e8-9359-19f8e3d9e9f3.png)

100MB connection would never take 4:18 minutes to do so. Notice it then again stalls after `sudo apt install git` was initiated and once again we see an IPv6 address...
![ipv6-issue-after-update](https://user-images.githubusercontent.com/2583357/37859914-eff4bc4a-2ef1-11e8-810f-5580049ec911.png)

If you could take a screen shot or paste more of the output from your device here it would help.

Possible related issue #400

**Comment by orionjb2001** [comment]
all working full speed now. :)
