### ISSUE TITLE
PiHole ad blocker co-existence? Logfile? Db installed?

### ISSUE THREAD

**Issue by frankk74** [jprochazka/adsb-receiver#424]
Hi,

First, many thanks for your scripts!!!

Background:

Raspbian on Raspberry Pi 3B+
adsb-receiver lastest version

Previously installed and running...

FlightAware manual 3.5.3
PiHole latest https://pi-hole.net

For this to work a slight modification to lighttpd conf was required (piaware+PiHole)

After running the install script and http install page ..

1. Coexist? I can’t find the main index page? For adsb-receiver? Sorry if this a rtfm question.

2 logfile? Also I was looking for a log file for the install of adsb-receiver and only found placeholder.txt

3. Reason for looking for logfile was I thought the script created a MySQL/mariaDB database? But show databases; did show me the name of gave for the dB?

4. Restarting install didn’t seem to by default allow me to reinstall fr24?

Thank you!

Frank

**Comment by frankk74** [comment]
Minor update.. I do get the login page at:

http://192.168.0.11/admin/login.php

Which happens to be PiHole’s default login :-( which probably means for the short term one or the other..

But when I enter my credentials I get the same URL but with a blank page?

Thx

Frank

**Comment by jprochazka** [comment]
1) I am not familiar with PiHole. I only installed it once and had it in place for only a couple days before removing it from my network due to issues. This being said I am not sure what port PiHole is bound to in lighttpd. If it is port 80 there may be issues. The lighttpd configuration for the portal is located in the file `/etc/lighttpd/conf-available/89-adsb-portal.conf`. The default page should be index.php. See if you can access the page using the full URL plus index.php.

2) The log file is only written when using the -l or --log-output flag when running install.sh. `./install.sh -l` I have been contemplating the creation of the file by default and more than likly will make this change in an upcoming release.

3) It should have created the database using the name you supplied. If the database was not created properly you should have received an error when installing the portal.

4) Once installed there is by default no option to reinstall fr24. Their script sets up its own update process once it has been ran so there is no need to address their installation script after it has been ran.

**Comment by jocamero** [comment]
I’m having the same #1 issue as @frankk74 Was anyone ever able to get this working?

**Comment by jprochazka** [comment]
At this time it would appear that PiHole and the portal do not coexist. At this time both PiHole and the portal want to use the directory /var/www/html. The portal will be changed in the future to run in a seaparate directory so that conflicts such as this are not encountered.

Please refer to issue #498
