### ISSUE TITLE
Performance Graphs source of excessive Disk I/O

### ISSUE THREAD

**Issue by joeyhagedorn** [jprochazka/adsb-receiver#431]
I've been running an adsb-reciever config for maybe 6 months, and experienced a flash SD card failure recently. As far as I can tell, this is due to the excessive writes caused by the Performance Graphs feature.

I'd like to request an option to run the performance graphs (collectd) and the visual display to a /tmpfs location, rather than directly writing to disk disk to eliminate this significant cause of disk I/O. I think an easy "Low Disk I/O" option in configuration would be really valuable in extending the reliability of these systems.

I also intend to move my syslog to a /tmpfs location, to avoid more disk writes. I hope eliminating those two sources will also lower the jdb2 writes, but frankly I'm not sure how to address the journaling issue 100%.

Here's the output of a couple minutes of: `sudo iotop -a -o` demonstrating the large writes caused by collectd.
```
Total DISK READ :       0.00 B/s | Total DISK WRITE :       0.00 B/s
Actual DISK READ:       0.00 B/s | Actual DISK WRITE:       0.00 B/s
  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND                                                     
   69 be/3 root          0.00 B    660.00 K  0.00 %  0.89 % [jbd2/mmcblk0p2-]
 2834 be/4 root          0.00 B      0.00 B  0.00 %  0.35 % [kworker/u8:3]
21574 be/4 root          0.00 B      0.00 B  0.00 %  0.35 % [kworker/u8:1]
  361 be/4 root          0.00 B     48.00 K  0.00 %  0.00 % rsyslogd -n [rs:main Q:Reg]
  785 be/4 root          0.00 B     15.67 M  0.00 %  0.00 % collectd [rrdtool queue]

```

**Comment by disquette38** [comment]
Hello,
I use https://github.com/azlux/log2ram

**Comment by jprochazka** [comment]
I tried adding a soultion such as this in an earlier version of the scripts. Things did not go well and a few receivers were trashed. At that point I decided I would leave it up to the users to set up their own solutions to deal with excesive wear caused by logging. I have done my best to streamline the lite version as much as possible to limit writes for those running SD cards without massive changes to the way the stock OS runs. There are just too many different devices, setups, and distros the scripts are capable of running on. 

I would be open to adding a wiki page to the project outlining how to do so if anyone wishes to share the steps they used to setup such a system successfully on their device.

As a side note external USB hard drives fairly inexpensivly which will negate this issue.

**Comment by joeyhagedorn** [comment]
Maybe a switch to turn off the performance graphs then? I'm not sure how I could do that and avoid having my configuration trashed on the next upgrade. I would be happy to file a separate bug for that if that's the best course of action.
