### ISSUE TITLE
receiver project v2.6.1 installer broken

### ISSUE THREAD

**Issue by orionjb2001** [jprochazka/adsb-receiver#436]
The installer is broken, only offering 1909 mutability install and then errors out in the flightaware piaware install

**Comment by orionjb2001** [comment]
same error code as previous post

**Comment by jprochazka** [comment]
Are you running on Ubuntu 17+?If so I removed the option to install dump1090-fa/PiAware due to issues not allowing piaware_puilder to successfully compile the applications. Please refer to the following issues pertaining to the reason the option to install these applications were removed.

https://github.com/jprochazka/adsb-receiver/issues/435
https://github.com/flightaware/piaware/issues/41
https://github.com/jprochazka/adsb-receiver/issues/435

Dump1090-fa/PiAware will be added again as an option for Ubuntu 17+ once a proper fix has been created. _**Keep in mind dump1090-fa/PiAware are available for install on Debian.**_
