### ISSUE TITLE
Error in ADS-B Exchange install script?

### ISSUE THREAD

**Issue by Toontje** [jprochazka/adsb-receiver#467]
------------------------------------------------------------------------------

  Checking for and removing any old style ADS-B Exchange setups if any exist...

  Checking for any preexisting older style setups...
  Checking if the netcat startup line is contained within the file /etc/rc.local...
  Checking for any running adsbexchange-netcat_maint.sh processes...
  Removing the netcat startup script line to the file /etc/rc.local...
**/home/pi/adsb-receiver/bash/feeders/adsbexchange.sh: line 154: /d: No such file or directory**

  Installing packages needed to build and fulfill dependencies...

  Checking if the package curl is installed...sed: -e expression #1, char 4: extra characters after command

**Comment by Romeo-Golf** [comment]
https://github.com/jprochazka/adsb-receiver/blame/d8e49c245d3117734537e3aa49b882e25f7bfbd2/bash/feeders/adsbexchange.sh#L154

Line 154: 
`sudo sed -i /$RECEIVER_BUILD_DIRECTORY\/adsbexchange\/adsbexchange-netcat_maint.sh &/d /etc/rc.local 2>&1`

**Comment by Romeo-Golf** [comment]
Doesnt seem worth creating a branch to fix these but there are a number of unquoted sed strings which will fail when expected to look for a string with whitespace in it :/

**Comment by jprochazka** [comment]
In this particular case as well as the case with any other unquoted sed command I am not looking for white spaces so there is no need to "fix" them. To go back and quote them would be pointless for sure.

The problem is as the error states: "No such file or directory" which has nothing to do with the RegEx portion of the sed command. This is more than likely referring to the system not being able to find /etc/rc.local which on most newer distros using systemd no longer exists unless created by the user.

Either I need to remove the offending code which is very legacy anyways and only undid changes made to by the script before ADS-B Exchange introduced the ability to use mlat-client or check to make sure that rc.local in facts exists and if not skip the check.
