### ISSUE TITLE
limited web portal

### ISSUE THREAD

**Issue by ericgrand** [jprochazka/adsb-receiver#490]
I'm unable to activate the advanced function (flight logging) on my install:
-raspberry Pi 3
-raspbian lite
-last version of adsb-receiver 3.6.3...

I can't access the <IP_ADRESS>/install page

Is there something I'm missing?

**Comment by radiostationx** [comment]
Did you login to the pi via PuTTy first ?
at the pi command line in a PuTTy terminal window
`cd adsb-receiver`
`./install.sh`
Follow the instructions to install portal.
When complete you should be able to open a browser and complete your setup with
<IP_ADRESS>/install

**Comment by ericgrand** [comment]
Yes, all setup is performed through PuTTy, including running the install script. I had access to the install page only once. Even after performing upgrade to 3.6.3, I can't have access anymore to the install page. The  browser switch directly to the blog page...
I don't know how I could access to the advanced portal. Even for the blog page, I can't add any comment.

Eric

**Comment by ryanbytes** [comment]
Same here. The install web page just returns a 404 error. Is this project still maintained?

**Comment by jprochazka** [comment]
@ryanbytes @ericgrand 

I will be setting up an advanced features portal tomorrow in order to work on a new version of the portal. At that time if I run into any issues I will be sure to work on getting a fix posted.

As to the question as to whether the project is still being maintained. A simple answer is yes as I find time. I am currently working on a new portal and plan to address the major issues posted in this tracker over the coming days. I have revived the webpage somewhat in order to post information on my recent work on the project.

https://www.adsbreceiver.net/2019/02/02/current-project-status/

**Comment by ryanbytes** [comment]
Good to hear! Thanks!

**Comment by tomwiley** [comment]
Also having the same problem, login is 'admin'  and default password the same yet I'm not able to lot in.

**Comment by jprochazka** [comment]
> login is 'admin' and default password

Are you using the login and password for the portal which you set during the portal setup process through your web browser? These credentials should be different from the pi user for security reasons.

**Comment by ryanbytes** [comment]
My mistake was not reading the final set of setup directions in the script. I thought the question that asked about using advanced features was the last so I always selected no. The setup would drop to the command line leaving the server login setup unfinished. Something like that anyway. I can't remember the steps exactly.

Once I got my head out of my rear I saw that the advanced features question wasn't the last! Hooray! I made the proper selection and got to the next screen which finished the web server login setup and completed the whole setup.

**Comment by tomwiley** [comment]
> 
> 
> > login is 'admin' and default password
> 
> Are you using the login and password for the portal which you set during the portal setup process through your web browser? These credentials should be different from the pi user for security reasons.

I have no option for setting a login and password for the portal during the setup process.  The last question I'm asked is if I want to continue to setup the Portal, then the final message is "Note that the Portal Setup is not complete" and that I have to go to the /Install portion of the webpage to complete it.  When I get to the page I get the message "ADS-B Receiver Portal Updated" and "Your Portal has been upgraded to v."  I can hit the "Settings" from above to go to the "Admin" page, but I have no valid login, so...

**Comment by jprochazka** [comment]
Should have posted my reponse to this issue here but thiniking it is the same post I would leave here.

issue #494

Not sure how but thinking your portal source somehow has the wrong version assigned to it and the upgrade script got skipped which adds the column causing the issue.
Do me a favor and look at the following files:
```
/var/www/html/classes/template.class.php
/var/www/install/index.php
```
Look for the variable in both named $thisVersion is it set to "2.7.0" if not change the version or better yet run ./install and chose to install the portal again and following the instructions after running the following commands:
```
git fetch --all
git reset --hard origin/master
```
If you are still having the same issue I will whip up a php file for you to execute to backrev the version stored so the upgrade takes place which adds the missing column.

**Comment by jprochazka** [comment]
Please refer to the tail end of Issue #494 if you are still having this issue. Push comes to shove at the most we may have to run a SQL query or two to get things up and running for you.

I should be by the computer most of Sunday working on v3 so I will keep an eye out here in case you do encounter any problems.

**Comment by jprochazka** [comment]
Please refer to the last part of issue #494. Push comes to shove a SQL query or two should get you up and running. I will be working on v3 come Sunday so I will be sure to keep an eye on the issue tracker as well then.

**Comment by jprochazka** [comment]
Please refer to the last part of issue #494. Push comes to shove a SQL query or two should get you up and running. I will be working on v3 come Sunday so I will be sure to keep an eye on the issue tracker as well then so feel free to comment if you are still having issues.

If you miss me Sunday I should be on sporatically in the evenings during the week. Cannot give exact days due to work and work related brain fry effecting my drive to code more than 8 hours in one day.

**Comment by jprochazka** [comment]
Please refer to the last part of issue #494. Push comes to shove a SQL query or two should get you up and running. I will be working on v3 come Sunday so I will be sure to keep an eye on the issue tracker as well then so feel free to comment if you are still having issues.

If you miss me Sunday I should be on sporatically in the evenings during the week. Cannot give exact days due to work and work related brain fry effecting my drive to write code more than 8 hours over the course of a day.

**Comment by ericgrand** [comment]
I have started a new install from scratch, by using the img:
adsb-receiver_2.6.3_dump1090-fa_raspbian-stretch-lite.img

I connect to the Pi via Putty and run initially raspi-config in order to setup wifi and locales in french.
After that, I run update of Pi with 
sudo apt-get update
then
sudo apt-get dist-upgrade

After that, I start the ADSBReceiver set with
cd ~/adsb-receiver/; ./install.sh
I perform
-the update search, then
-the Heywhatsthat configuration
-the "claim your PiAware device (I already have a feeder ID) so I select Yes to access the Flight Aware website from the same public IP
-then I select Yes for the Project Portal Setup
-then Yes for the advanced features
-I select MySQL for the Database
-Yes for for the database hosted locally
-the script then install the MySQL package

It is from then I have some doubts on the process...
I'm asked for the root PW... which is blan,k yet,
![root1](https://user-images.githubusercontent.com/34603451/54319376-b2bdf200-45e9-11e9-8d14-65190dd50709.jpg)
I then define a PW
![script2](https://user-images.githubusercontent.com/34603451/54319605-69ba6d80-45ea-11e9-8dd8-df77b79baad0.jpg)
and the script go on, asking me the name of a user with a password and the database name.
![MySQL1](https://user-images.githubusercontent.com/34603451/54307466-146f6380-45cc-11e9-9990-1efaec67ea90.jpg)
I then go to the portal setup through webaccess but I don't know which info I should put in the required field:
![portal1](https://user-images.githubusercontent.com/34603451/54319718-ca49aa80-45ea-11e9-9bef-c4b114d3be99.jpg)
What is the Database server? which user should I indicate? the one created through the script?
And the database name is the one created also through the script?

When I enter value I think are correct, I then complete the setup by giving details of administrator and after step 4, the next page is an error page...and I have access to nothing...None of the page are working anymore, even after a reboot.
Is there any "how to" for the noob available?...

**Comment by jprochazka** [comment]
> What is the Database server?

You chose to install MySQL/MariaDB locally so the answer is `localhost`.

> which user should I indicate? the one created through the script?

Correct, the non root user you specified during setup.
You will use the password you supplied during setup for this user as well.

> And the database name is the one created also through the script?

Again you are correct.

> after step 4, the next page is an error page...

Can you share any error messages you see in the following log file?
`sudo nano /var/log/lighttpd/error.log`

**Comment by ericgrand** [comment]
Thanks for your feedback!
I will re-do an install from scratch and see if I can achieve it!
Else I will share the log file with you!

**Comment by jprochazka** [comment]
Remember to keep notes on users and passwords as well as the database name you create during the installation process and you should be good to go if not let me know.

**Comment by ericgrand** [comment]
All is now working properly! Many thanks for your support. The mess was coming from the database server which was incorrectly understood on my side...

**Comment by jprochazka** [comment]
Anytime. Glad to see you up and running now.
