### ISSUE TITLE
Dump1090-fa does not build

### ISSUE THREAD

**Issue by cwalker51** [jprochazka/adsb-receiver#500]
m a nube just following instructions. I get this error when I 
./install.shI

sdr_bladerf.c: In function ‘show_config’:
sdr_bladerf.c:116:76: error: passing argument 3 of ‘bladerf_get_frequency’ from incompatible pointer type [-Werror=incompatible-pointer-types]
         (status = bladerf_get_frequency(BladeRF.device, BLADERF_MODULE_RX, &freq)) < 0 ||
                                                                            ^
In file included from sdr_bladerf.c:23:0:
/usr/include/libbladeRF.h:1275:15: note: expected ‘bladerf_frequency * {aka long unsigned int *}’ but argument is of type ‘unsigned int *’
 int CALL_CONV bladerf_get_frequency(struct bladerf *dev,
               ^~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Makefile:41: recipe for target 'sdr_bladerf.o' failed
make[2]: *** [sdr_bladerf.o] Error 1
make[2]: Leaving directory '/root/adsb-receiver/build/dump1090-fa/dump1090'
dh_auto_build: make -j1 RTLSDR=yes BLADERF=yes DUMP1090_VERSION=3.6.3 returned exit code 2
debian/rules:23: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 2
make[1]: Leaving directory '/root/adsb-receiver/build/dump1090-fa/dump1090'
debian/rules:32: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

  Entering the dump1090-fa build directory...
  Installing the dump1090-fa package...

dpkg: error: cannot access archive 'dump1090-fa_3.6.3_*.deb': No such file or directory

  Checking that the dump1090-fa package was installed properly...

  INSTALLATION HALTED!
  UNABLE TO INSTALL A REQUIRED PACKAGE.
  SETUP HAS BEEN TERMINATED!

The package "dump1090-fa" could not be installed.

**Comment by jprochazka** [comment]
I am on it and there will be a solution committed shortly. The solution is not building the latest bladeRF libraries and instead installing the older bladerf libraries available via most distro repositories.

**Comment by cwalker51** [comment]
Great!! Thanks Joe

**Comment by cwalker51** [comment]
Working Great. THANKS!!
Surprised I never got a notification of solution. Or maybe I just missed It..

Thanks Again

**Comment by jprochazka** [comment]
Don't feel bad. I have been beating my head against a wall for months and guess what? No one ever told me never to use the maintainer version. I always went off the instructions supplied by FlightAware. From the dump1090-0fa README:

> Dependencies - bladeRF
> You will need a build of libbladeRF. You can build packages from source:
> $ git clone https://github.com/Nuand/bladeRF.git $ cd bladeRF $ dpkg-buildpackage -b
> Or Nuand has some build/install instructions including an Ubuntu PPA at https://github.com/Nuand/bladeRF/wiki/Getting-Started:-Linux
> Or FlightAware provides armhf packages as part of the piaware repository; see https://flightaware.com/adsb/piaware/install

FYI the instructions are wrong at this point.

> $ git clone https://github.com/Nuand/bladeRF.git $ cd bladeRF $ dpkg-buildpackage -b

This builds the latest 2018 build which will never work being they changed a variable type which dump1090-fa uses.

**Comment by jprochazka** [comment]
Fix merged into master branch.

**Comment by mutability** [comment]
Those instructions are for building on jessie (as the header says); jessie doesn't have a packaged libbladerf.

**Comment by mutability** [comment]
I added explicit instructions for stretch.

**Comment by jprochazka** [comment]
> Those instructions are for building on jessie (as the header says); jessie doesn't have a packaged libbladerf.

FOllowing the instructions will build libbladerf2 which would not work even on Jessie since they changed the variable type. What I was suggesting is modifying the instructions to pull maybe the libbladeRF_v1.9.1 tag from their repository?

**Comment by mutability** [comment]
Well, the dev branch should build against libbladerf2 now anyway.

**Comment by jprochazka** [comment]
Cool deal. In the meantime I made a slight mod to your readme. Basically added the line git checkout 2017.12-rc1 which should build a package which matches the version maintained by Debian.

https://github.com/flightaware/dump1090/pull/43

**Comment by henkiejan1** [comment]
Excuse me. I have triest your instruction for bladerf because i got the same error as above. So i did the git checkout but now also i got a different error... Any idea how to simple fix this?

`In file included from /usr/include/string.h:495,
                 from /home/hj/bladeRF/host/libraries/libbladeRF/src/device_identifier.c:22:
In function ‘strncpy’,
    inlined from ‘handle_serial’ at /home/hj/bladeRF/host/libraries/libbladeRF/src/device_identifier.c:140:5,
    inlined from ‘str2devinfo’ at /home/hj/bladeRF/host/libraries/libbladeRF/src/device_identifier.c:229:30:
/usr/include/aarch64-linux-gnu/bits/string_fortified.h:106:10: error: ‘__builtin___strncpy_chk’ output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/hj/bladeRF/host/libraries/libbladeRF/src/device_identifier.c: In function ‘str2devinfo’:
/home/hj/bladeRF/host/libraries/libbladeRF/src/device_identifier.c:119:11: note: length computed here
  119 |     len = strlen(value);
      |           ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [host/libraries/libbladeRF/CMakeFiles/libbladerf_shared.dir/build.make:157: host/libraries/libbladeRF/CMakeFiles/libbladerf_shared.dir/src/device_identifier.c.o] Error 1
make[3]: Leaving directory '/home/hj/bladeRF/obj-aarch64-linux-gnu'
make[2]: *** [CMakeFiles/Makefile2:830: host/libraries/libbladeRF/CMakeFiles/libbladerf_shared.dir/all] Error 2
make[2]: Leaving directory '/home/hj/bladeRF/obj-aarch64-linux-gnu'
make[1]: *** [Makefile:133: all] Error 2
make[1]: Leaving directory '/home/hj/bladeRF/obj-aarch64-linux-gnu'
dh_auto_build: error: cd obj-aarch64-linux-gnu && make -j1 returned exit code 2
make: *** [debian/rules:46: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
`
